import sys
from typing import List, Optional
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from app.config import settings
from app.agents.orchestrator import orchestrator

# Initialize FastAPI App
app = FastAPI(
    title="EmployeeMate",
    description="Production-Ready Dual-Agent Employee AI Assistant with RAG & HR operations",
    version="1.0.0"
)

# Configure CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request & Response Models
class ChatRequest(BaseModel):
    prompt: str = Field(..., description="User query or instruction", example="What is the WFH policy and how many leaves does EMP001 have?")
    emp_id: Optional[str] = Field(None, description="Optional Employee ID for HR context", example="EMP001")
    actor_role: Optional[str] = Field("EMPLOYEE", description="Role of the user sending request: 'EMPLOYEE' or 'HR'", example="EMPLOYEE")
    history: Optional[List[dict]] = Field(default_factory=list, description="Recent conversation history")


class ChatResponse(BaseModel):
    answer: str = Field(..., description="Final answer generated by the system")
    sources: List[str] = Field(default_factory=list, description="List of source policy files retrieved by RAG")
    tools_used: List[str] = Field(default_factory=list, description="List of tools/methods executed during request")
    agent_routed: str = Field(..., description="The name of the agent or orchestrator handling the request")
    updated_employees: Optional[List[dict]] = Field(None, description="Live updated employee profiles state")


# Global Exception Handling
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "detail": f"An unexpected error occurred: {str(exc)}",
            "type": exc.__class__.__name__
        }
    )


# --- Core Logic Functions ---
def execute_health_check():
    return {
        "status": "healthy",
        "app_env": getattr(settings, "app_env", "production"),
        "vector_store_initialized": orchestrator.knowledge_agent.rag.vector_store is not None
    }


def execute_get_employees():
    return orchestrator.hr_agent.db.get_all_employees()


def execute_chat(request_payload: ChatRequest):
    if request_payload.prompt is None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Prompt field cannot be null."
        )

    try:
        result = orchestrator.route_and_execute(
            prompt=request_payload.prompt,
            emp_id=request_payload.emp_id,
            history=request_payload.history,
            actor_role=request_payload.actor_role or "EMPLOYEE"
        )
        live_employees = orchestrator.hr_agent.db.get_all_employees()["data"]
        return ChatResponse(
            answer=result["answer"],
            sources=result.get("sources", []),
            tools_used=result.get("tools_used", []),
            agent_routed=result.get("agent_routed", "Unknown"),
            updated_employees=live_employees
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing chat request: {str(e)}"
        )


# --- Standard Routes ---
@app.get("/", tags=["Health"])
async def root():
    return {
        "message": "Welcome to EmployeeMate API",
        "docs": "/docs",
        "health": "/health"
    }


@app.get("/health", tags=["Health"])
async def health_check():
    return execute_health_check()


@app.get("/employees", tags=["Employees"])
async def get_employees():
    """
    GET /employees Endpoint
    Returns live employee database records with real-time leave balances.
    """
    return execute_get_employees()


@app.post("/chat", response_model=ChatResponse, status_code=status.HTTP_200_OK, tags=["Chat Assistant"])
async def chat(request_payload: ChatRequest):
    """
    POST /chat Endpoint
    Accepts user prompt, optional employee ID, actor role, and conversation history.
    Routes to KnowledgeAgent, HRAgent, or Orchestrator_MultiAgent with RBAC enforcement.
    """
    return execute_chat(request_payload)


# --- Serverless `/api` Alias Routes (for Vercel Routing) ---
@app.get("/api", tags=["Health Serverless"], include_in_schema=False)
async def root_api():
    return await root()


@app.get("/api/health", tags=["Health Serverless"], include_in_schema=False)
async def health_check_api():
    return execute_health_check()


@app.get("/api/employees", tags=["Employees Serverless"], include_in_schema=False)
async def get_employees_api():
    return execute_get_employees()


@app.post("/api/chat", response_model=ChatResponse, status_code=status.HTTP_200_OK, tags=["Chat Assistant Serverless"], include_in_schema=False)
async def chat_api(request_payload: ChatRequest):
    return execute_chat(request_payload)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)